// Quantitative Data & Analysis — Question Bank
// Each question: { id, topic, type (single/multi/tf), q_zh, q_en, opts (array of {zh,en}), correct (index or array), exp_zh, exp_en }
window.QDA_QUIZ = {
topics: [
  {id:'qpcr',         name_zh:'qPCR / RT-qPCR',         name_en:'qPCR / RT-qPCR'},
  {id:'wb',           name_zh:'Western Blot',           name_en:'Western Blot'},
  {id:'elisa',        name_zh:'ELISA & 標準曲線',       name_en:'ELISA & Standard Curves'},
  {id:'flow',         name_zh:'Flow Cytometry',          name_en:'Flow Cytometry'},
  {id:'image',        name_zh:'影像定量',                name_en:'Image Quantification'},
  {id:'eda',          name_zh:'EDA 探索性分析',          name_en:'EDA'},
  {id:'ht',           name_zh:'假設檢定',                name_en:'Hypothesis Testing'},
  {id:'mtc',          name_zh:'多重比較校正',            name_en:'Multiple Testing'},
  {id:'reg',          name_zh:'回歸與劑量反應',          name_en:'Regression / Dose-Response'},
  {id:'es',           name_zh:'效應量與 Power',         name_en:'Effect Size & Power'},
  {id:'omics',        name_zh:'組學定量分析',            name_en:'Omics Quantification'},
  {id:'viz',          name_zh:'資料視覺化',              name_en:'Visualization'},
  {id:'repro',        name_zh:'再現性與報告標準',        name_en:'Reproducibility'},
  {id:'ml',           name_zh:'AI / ML 量化分析',        name_en:'AI / ML'}
],
questions: [
  // ===== qPCR =====
  {id:'qpcr-1', topic:'qpcr', type:'single',
   q_zh:'標準曲線 slope = −3.32，PCR 效率最接近？', q_en:'Standard curve slope = −3.32. Approximate PCR efficiency?',
   opts:[{zh:'80%',en:'80%'},{zh:'90%',en:'90%'},{zh:'100%',en:'100%'},{zh:'110%',en:'110%'}],
   correct:2, exp_zh:'E = 10^(−1/−3.32) − 1 ≈ 1.0 → 100%。', exp_en:'E = 10^(−1/−3.32) − 1 ≈ 1.0 → 100%.'},
  {id:'qpcr-2', topic:'qpcr', type:'multi',
   q_zh:'MIQE 2.0 (2025) 新增的要求包括？（複選）', q_en:'New MIQE 2.0 (2025) requirements include? (multi)',
   opts:[{zh:'必須報告 LOD/LOQ 的 95% CI',en:'Report 95% CI for LOD/LOQ'},
         {zh:'禁止使用 SYBR Green',en:'Ban SYBR Green'},
         {zh:'強制提供原始資料以供再分析',en:'Mandatory raw data sharing'},
         {zh:'效率校正的目標量',en:'Efficiency-corrected target quantities'}],
   correct:[0,2,3], exp_zh:'MIQE 2.0 三大新增重點：LOD/LOQ CI、原始資料公開、效率校正定量。', exp_en:'Three additions: LOD/LOQ CIs, raw data sharing, efficiency-corrected quantities.'},
  {id:'qpcr-3', topic:'qpcr', type:'tf',
   q_zh:'統計 fold change 可直接用原始 FC 跑 t-test。', q_en:'You can run t-test directly on raw fold change.',
   opts:[{zh:'True',en:'True'},{zh:'False',en:'False'}],
   correct:1, exp_zh:'FC 為對數常態分佈，必須轉 log2(FC) 或直接用 ΔCt。', exp_en:'FC is log-normal — transform to log2(FC) or use ΔCt directly.'},
  {id:'qpcr-4', topic:'qpcr', type:'single',
   q_zh:'下列何者最不需要 PCR 標準曲線？', q_en:'Which does NOT require a standard curve?',
   opts:[{zh:'相對定量 ΔΔCt',en:'Relative ΔΔCt'},
         {zh:'絕對定量 (qPCR)',en:'Absolute qPCR'},
         {zh:'數位 PCR (dPCR)',en:'Digital PCR (dPCR)'},
         {zh:'Pfaffl 校正',en:'Pfaffl correction'}],
   correct:2, exp_zh:'dPCR 透過反應分隔與 Poisson 計算絕對拷貝數，不需標準曲線。', exp_en:'dPCR uses partitioning + Poisson for absolute counts — no curve needed.'},
  {id:'qpcr-5', topic:'qpcr', type:'single',
   q_zh:'缺氧條件下哪個 reference gene 最不可靠？', q_en:'Which reference is least reliable under hypoxia?',
   opts:[{zh:'GAPDH',en:'GAPDH'},{zh:'RPL13A',en:'RPL13A'},{zh:'TBP',en:'TBP'},{zh:'YWHAZ',en:'YWHAZ'}],
   correct:0, exp_zh:'GAPDH 在低氧下會顯著上升（HIF 調控）。', exp_en:'GAPDH is HIF-regulated and rises under hypoxia.'},

  // ===== Western Blot =====
  {id:'wb-1', topic:'wb', type:'single',
   q_zh:'ECL 化學發光的線性動態範圍約是？', q_en:'Approximate linear dynamic range of ECL?',
   opts:[{zh:'0.5 log',en:'0.5 log'},{zh:'1.5 log',en:'1.5 log'},{zh:'3 log',en:'3 log'},{zh:'5 log',en:'5 log'}],
   correct:1, exp_zh:'ECL 約 1.5 log；螢光二抗約 3 log。', exp_en:'ECL ~1.5 log; fluorescent secondary ~3 log.'},
  {id:'wb-2', topic:'wb', type:'tf',
   q_zh:'飽和 band 仍可用 ImageJ 量化「相對」差異。', q_en:'Saturated bands can still be quantified for relative differences.',
   opts:[{zh:'True',en:'True'},{zh:'False',en:'False'}],
   correct:1, exp_zh:'飽和區無線性關係，任何「相對」量化都失真。', exp_en:'Saturated region is non-linear — any "relative" measurement is distorted.'},
  {id:'wb-3', topic:'wb', type:'multi',
   q_zh:'下列哪些屬於 total protein normalization？（複選）', q_en:'Which are total protein normalization? (multi)',
   opts:[{zh:'Ponceau S 染色',en:'Ponceau S staining'},{zh:'GAPDH 抗體',en:'GAPDH antibody'},
         {zh:'Stain-free 膠',en:'Stain-free gel'},{zh:'REVERT total protein',en:'REVERT total protein'}],
   correct:[0,2,3], exp_zh:'TPN 包括 Ponceau、Stain-free、REVERT；GAPDH 屬 housekeeping。', exp_en:'TPN: Ponceau, Stain-free, REVERT. GAPDH = housekeeping.'},
  {id:'wb-4', topic:'wb', type:'single',
   q_zh:'2025 PLOS ONE 研究顯示 TPN 比 GAPDH 的 CV 低約？', q_en:'2025 PLOS ONE: TPN CV vs GAPDH is lower by?',
   opts:[{zh:'5-10%',en:'5-10%'},{zh:'20-30%',en:'20-30%'},{zh:'50-80%',en:'50-80%'},{zh:'90%',en:'90%'}],
   correct:2, exp_zh:'Hagstrom 2025 報告 50-80% 降幅。', exp_en:'Hagstrom 2025: 50-80% reduction in CV.'},

  // ===== ELISA =====
  {id:'elisa-1', topic:'elisa', type:'single',
   q_zh:'LOQ 標準定義為？', q_en:'Standard definition of LOQ?',
   opts:[{zh:'blank + 1·SD',en:'blank + 1·SD'},{zh:'blank + 3·SD',en:'blank + 3·SD'},
         {zh:'blank + 10·SD (CV≤20%)',en:'blank + 10·SD (CV≤20%)'},{zh:'2× LOD',en:'2× LOD'}],
   correct:2, exp_zh:'LOQ = blank mean + 10·SD 且 CV ≤ 20%。', exp_en:'LOQ = blank + 10·SD with CV ≤ 20%.'},
  {id:'elisa-2', topic:'elisa', type:'single',
   q_zh:'競爭型或 multiplex ELISA 通常需要哪種擬合？', q_en:'Competitive or multiplex ELISA usually needs?',
   opts:[{zh:'線性回歸',en:'Linear'},{zh:'4-PL (對稱)',en:'4-PL (symmetric)'},
         {zh:'5-PL (不對稱)',en:'5-PL (asymmetric)'},{zh:'多項式',en:'Polynomial'}],
   correct:2, exp_zh:'競爭型/multiplex 曲線常不對稱，需 5-PL 的 g 參數。', exp_en:'Asymmetric S-curves need 5-PL asymmetry parameter g.'},
  {id:'elisa-3', topic:'elisa', type:'tf',
   q_zh:'樣品 OD 高於最高標準品時可外插曲線報告濃度。', q_en:'Sample OD above top standard can be extrapolated.',
   opts:[{zh:'True',en:'True'},{zh:'False',en:'False'}],
   correct:1, exp_zh:'絕不外插；應稀釋樣品重新分析。', exp_en:'Never extrapolate; dilute and re-run.'},
  {id:'elisa-4', topic:'elisa', type:'single',
   q_zh:'Spike-and-recovery 應在多少範圍才合格？', q_en:'Acceptable spike-and-recovery range?',
   opts:[{zh:'10–50%',en:'10–50%'},{zh:'50–80%',en:'50–80%'},
         {zh:'80–120%',en:'80–120%'},{zh:'必須 100%',en:'Exactly 100%'}],
   correct:2, exp_zh:'FDA 與多數方法驗證指南要求 80–120%。', exp_en:'FDA and most validation guidelines: 80–120%.'},

  // ===== Flow =====
  {id:'flow-1', topic:'flow', type:'single',
   q_zh:'現代設 gate 的金標準對照？', q_en:'Modern gold-standard gating control?',
   opts:[{zh:'Isotype',en:'Isotype'},{zh:'Unstained',en:'Unstained'},
         {zh:'FMO',en:'FMO'},{zh:'PBS 對照',en:'PBS control'}],
   correct:2, exp_zh:'FMO 反映抗體在你 panel 中真實 spillover spread。', exp_en:'FMO captures actual spillover spread in your panel.'},
  {id:'flow-2', topic:'flow', type:'tf',
   q_zh:'報告 MFI 時應使用算術平均 (mean)。', q_en:'Arithmetic mean is appropriate for MFI.',
   opts:[{zh:'True',en:'True'},{zh:'False',en:'False'}],
   correct:1, exp_zh:'螢光分佈右偏，應用 median 或 geometric mean。', exp_en:'Fluorescence is right-skewed — use median or geometric mean.'},
  {id:'flow-3', topic:'flow', type:'multi',
   q_zh:'下列哪些屬於 flow 流程的關鍵控制？（複選）', q_en:'Which are key flow controls? (multi)',
   opts:[{zh:'Single-stain compensation beads',en:'Single-stain compensation beads'},
         {zh:'Live/dead 染色',en:'Live/dead stain'},
         {zh:'FMO',en:'FMO'},
         {zh:'Isotype 必須做',en:'Isotype mandatory'}],
   correct:[0,1,2], exp_zh:'isotype 已被淘汰，其餘三項皆為現代必備。', exp_en:'Isotype is deprecated; the other three are essential.'},

  // ===== Image =====
  {id:'image-1', topic:'image', type:'single',
   q_zh:'影像定量的最低檔案格式要求？', q_en:'Minimum image format for quantification?',
   opts:[{zh:'8-bit JPEG',en:'8-bit JPEG'},{zh:'16-bit TIFF',en:'16-bit TIFF'},
         {zh:'PNG-24',en:'PNG-24'},{zh:'WebP',en:'WebP'}],
   correct:1, exp_zh:'JPEG 為有損壓縮會破壞動態範圍。', exp_en:'JPEG is lossy and breaks dynamic range.'},
  {id:'image-2', topic:'image', type:'single',
   q_zh:'共定位前必要的前處理？', q_en:'Required preprocessing before colocalization?',
   opts:[{zh:'增亮對比',en:'Increase brightness'},{zh:'背景扣除',en:'Background subtraction'},
         {zh:'轉灰階',en:'Grayscale conversion'},{zh:'下採樣',en:'Downsampling'}],
   correct:1, exp_zh:'背景同步存在於兩通道時會虛假拉高 Pearson r。', exp_en:'Common background in both channels falsely inflates Pearson r.'},
  {id:'image-3', topic:'image', type:'tf',
   q_zh:'Pearson r 與 Manders M1 衡量相同事情。', q_en:'Pearson r and Manders M1 measure the same thing.',
   opts:[{zh:'True',en:'True'},{zh:'False',en:'False'}],
   correct:1, exp_zh:'Pearson 量強度線性相關；Manders 量重疊比例。', exp_en:'Pearson = intensity correlation; Manders = overlap fraction.'},

  // ===== EDA =====
  {id:'eda-1', topic:'eda', type:'single',
   q_zh:'n=1000 跑 Shapiro 拿到 p=0.01 該如何解讀？', q_en:'n=1000 with Shapiro p=0.01 — interpret?',
   opts:[{zh:'嚴重非常態必改無母數',en:'Strongly non-normal — switch'},
         {zh:'微小偏離；查 Q-Q 與偏度',en:'Trivial deviation; inspect Q-Q'},
         {zh:'樣本太多',en:'Too many samples'},
         {zh:'參數錯誤',en:'Parameter error'}],
   correct:1, exp_zh:'大樣本下檢定敏感度過高；CLT 已保證 t/ANOVA 穩健。', exp_en:'Large n inflates sensitivity; CLT makes t/ANOVA robust.'},
  {id:'eda-2', topic:'eda', type:'single',
   q_zh:'最穩健的離群值偵測？', q_en:'Most robust outlier detection?',
   opts:[{zh:'Mean±3·SD',en:'Mean±3·SD'},{zh:'MAD±3',en:'MAD±3'},
         {zh:'Z-score=2',en:'Z-score=2'},{zh:'平均值×2',en:'2×mean'}],
   correct:1, exp_zh:'MAD 不受極端值影響，最穩健 (Leys 2013)。', exp_en:'MAD ignores extremes — most robust (Leys 2013).'},
  {id:'eda-3', topic:'eda', type:'tf',
   q_zh:'Anscombe quartet 的訊息是「永遠先畫圖」。', q_en:'Anscombe quartet teaches: "always plot first."',
   opts:[{zh:'True',en:'True'},{zh:'False',en:'False'}],
   correct:0, exp_zh:'是。四組摘要統計相同但圖形截然不同。', exp_en:'Yes — identical summaries, very different plots.'},

  // ===== Hypothesis Testing =====
  {id:'ht-1', topic:'ht', type:'single',
   q_zh:'現代推薦的兩組獨立樣本預設檢定？', q_en:'Modern default two-sample test?',
   opts:[{zh:"Student's t",en:"Student's t"},{zh:"Welch's t",en:"Welch's t"},
         {zh:'Mann-Whitney',en:'Mann-Whitney'},{zh:'paired t',en:'paired t'}],
   correct:1, exp_zh:"Delacre 2017：Welch's t 預設，不假設等變異。", exp_en:"Delacre 2017: Welch's t as default — no equal variance assumption."},
  {id:'ht-2', topic:'ht', type:'multi',
   q_zh:'ASA 2016 的核心提醒包括？（複選）', q_en:'ASA 2016 key reminders? (multi)',
   opts:[{zh:'p < 0.05 不等於重要',en:'p < 0.05 ≠ important'},
         {zh:'p 是「假設為真」的機率',en:'p = probability hypothesis is true'},
         {zh:'不能僅以 p 值決策',en:"Don't use p alone for decisions"},
         {zh:'p 衡量資料與模型的不相容程度',en:'p measures data-model incompatibility'}],
   correct:[0,2,3], exp_zh:'第二項是常見誤解；其餘三項皆為 ASA 原則。', exp_en:'#2 is a misconception; the others are ASA principles.'},
  {id:'ht-3', topic:'ht', type:'single',
   q_zh:'2×2 表期望次數 < 5 的最佳檢定？', q_en:'Best test for 2×2 with expected count < 5?',
   opts:[{zh:'Chi-square',en:'Chi-square'},{zh:'Fisher exact',en:'Fisher exact'},
         {zh:'t-test',en:'t-test'},{zh:'ANOVA',en:'ANOVA'}],
   correct:1, exp_zh:'低期望次數時 chi-square 不準，Fisher exact 更可靠。', exp_en:'Chi-square unreliable at low expected counts → Fisher exact.'},

  // ===== MTC =====
  {id:'mtc-1', topic:'mtc', type:'single',
   q_zh:'組學 DE 分析最常用校正？', q_en:'Most common omics DE correction?',
   opts:[{zh:'Bonferroni',en:'Bonferroni'},{zh:'BH-FDR',en:'BH-FDR'},
         {zh:'Holm',en:'Holm'},{zh:'Tukey HSD',en:'Tukey HSD'}],
   correct:1, exp_zh:'BH-FDR (Benjamini-Hochberg 1995) 為組學標準。', exp_en:'BH-FDR (Benjamini-Hochberg 1995) is the omics standard.'},
  {id:'mtc-2', topic:'mtc', type:'tf',
   q_zh:'Bonferroni 控制的是 FDR。', q_en:'Bonferroni controls FDR.',
   opts:[{zh:'True',en:'True'},{zh:'False',en:'False'}],
   correct:1, exp_zh:'Bonferroni 控制 FWER；BH 控制 FDR。', exp_en:'Bonferroni controls FWER; BH controls FDR.'},
  {id:'mtc-3', topic:'mtc', type:'single',
   q_zh:'多組 vs 同一對照組比較最適合的 post-hoc？', q_en:'Best post-hoc for multi-group vs single control?',
   opts:[{zh:'Tukey HSD',en:'Tukey HSD'},{zh:"Dunnett's",en:"Dunnett's"},
         {zh:'Bonferroni only',en:'Bonferroni only'},{zh:'BH',en:'BH'}],
   correct:1, exp_zh:"Dunnett's 特化於多組 vs 對照比較，功效高於 Tukey。", exp_en:"Dunnett's is specialized for multi-vs-control with higher power."},

  // ===== Regression =====
  {id:'reg-1', topic:'reg', type:'single',
   q_zh:'資料含 outlier 且非線性單調，相關係數應選？', q_en:'Outlier + monotonic non-linear: which correlation?',
   opts:[{zh:'Pearson r',en:'Pearson r'},{zh:'Spearman ρ',en:'Spearman ρ'},
         {zh:'Cosine sim.',en:'Cosine sim.'},{zh:'R²',en:'R²'}],
   correct:1, exp_zh:'Spearman 排名相關穩健於 outlier 與非線性單調。', exp_en:'Spearman ranks are robust to outliers and monotonic non-linearity.'},
  {id:'reg-2', topic:'reg', type:'tf',
   q_zh:'Lineweaver-Burk 雙倒數圖是估 Vmax/Km 的最佳方法。', q_en:'Lineweaver-Burk is the best way to estimate Vmax/Km.',
   opts:[{zh:'True',en:'True'},{zh:'False',en:'False'}],
   correct:1, exp_zh:'線性化扭曲誤差結構；現代教科書一致反對。', exp_en:'Linearization distorts errors; rejected by modern textbooks.'},
  {id:'reg-3', topic:'reg', type:'single',
   q_zh:'Hill slope = 2 表示？', q_en:'Hill slope = 2 means?',
   opts:[{zh:'1:1 binding',en:'1:1 binding'},{zh:'Positive cooperativity',en:'Positive cooperativity'},
         {zh:'Negative cooperativity',en:'Negative cooperativity'},{zh:'IC50 = 2',en:'IC50 = 2'}],
   correct:1, exp_zh:'Hill n > 1 為正向協同 (positive cooperativity)。', exp_en:'Hill n > 1 = positive cooperativity.'},

  // ===== Effect Size & Power =====
  {id:'es-1', topic:'es', type:'single',
   q_zh:'n=10、p=0.4 應做？', q_en:'n=10, p=0.4 — what to do?',
   opts:[{zh:'Post hoc power',en:'Post hoc power'},
         {zh:'Sensitivity analysis',en:'Sensitivity analysis'},
         {zh:'刪 3 個樣本',en:'Drop 3 samples'},{zh:'改無母數',en:'Switch to non-parametric'}],
   correct:1, exp_zh:'Sensitivity analysis 給定 n、α、power，算最小可偵測 d。', exp_en:'Sensitivity analysis: given n, α, power → minimum detectable d.'},
  {id:'es-2', topic:'es', type:'single',
   q_zh:'小樣本 (n=8) 兩組比較最佳 ES？', q_en:'Two-group small sample (n=8) best ES?',
   opts:[{zh:"Cohen's d",en:"Cohen's d"},{zh:"Hedges' g",en:"Hedges' g"},
         {zh:'η²',en:'η²'},{zh:'Pearson r',en:'Pearson r'}],
   correct:1, exp_zh:"Hedges' g 對小樣本做 (1-3/(4df-1)) 校正。", exp_en:"Hedges' g applies the (1-3/(4df-1)) small-sample correction."},
  {id:'es-3', topic:'es', type:'tf',
   q_zh:'Post hoc power 與 p 值一一對應，無法提供新資訊。', q_en:'Post-hoc power is one-to-one with p — adds no info.',
   opts:[{zh:'True',en:'True'},{zh:'False',en:'False'}],
   correct:0, exp_zh:'Hoenig & Heisey 2001 正是此論點的代表文獻。', exp_en:'Hoenig & Heisey 2001 made this exact argument.'},

  // ===== Omics =====
  {id:'omics-1', topic:'omics', type:'single',
   q_zh:'樣本間可比的 RNA-seq 量化單位？', q_en:'Which unit is comparable across samples?',
   opts:[{zh:'Raw counts',en:'Raw counts'},{zh:'RPKM/FPKM',en:'RPKM/FPKM'},
         {zh:'TPM',en:'TPM'},{zh:'CPM raw',en:'CPM raw'}],
   correct:2, exp_zh:'TPM 樣本總和固定為 1e6，跨樣本可比 (Wagner 2012)。', exp_en:'TPM sums to 1e6 per sample, hence comparable (Wagner 2012).'},
  {id:'omics-2', topic:'omics', type:'tf',
   q_zh:'DE 分析可直接把 TPM 餵 t-test。', q_en:'You can run t-test on TPM for DE.',
   opts:[{zh:'True',en:'True'},{zh:'False',en:'False'}],
   correct:1, exp_zh:'TPM 違反 NB 分佈假設；應給 DESeq2 raw counts。', exp_en:'TPM violates NB; feed raw counts to DESeq2.'},
  {id:'omics-3', topic:'omics', type:'single',
   q_zh:'排序 DE 基因應用？', q_en:'Rank DE genes by?',
   opts:[{zh:'Raw log2FC',en:'Raw log2FC'},
         {zh:'apeglm shrunken log2FC',en:'apeglm shrunken log2FC'},
         {zh:'−log10(p)',en:'−log10(p)'},{zh:'TPM ratio',en:'TPM ratio'}],
   correct:1, exp_zh:'Zhu 2018 apeglm 縮小低 count 基因的噪音膨脹。', exp_en:'Zhu 2018 apeglm shrinks noisy low-count log2FCs.'},

  // ===== Visualization =====
  {id:'viz-1', topic:'viz', type:'single',
   q_zh:'Weissgerber 2015 PLOS Biology 主要建議？', q_en:'Weissgerber 2015 PLOS Bio main message?',
   opts:[{zh:'禁 ggplot2',en:'Ban ggplot2'},
         {zh:'以 dot/box 顯示原始資料',en:'Show raw data via dot/box'},
         {zh:'必須 3D',en:'Use 3D'},{zh:'用 pie',en:'Use pie'}],
   correct:1, exp_zh:'bar+SEM 隱藏分佈；改 dot/box plot。', exp_en:'bar+SEM hides distribution; switch to dot/box.'},
  {id:'viz-2', topic:'viz', type:'single',
   q_zh:'≥4 集合交集用？', q_en:'For ≥4 set intersections, use?',
   opts:[{zh:'Venn',en:'Venn'},{zh:'UpSet plot',en:'UpSet plot'},
         {zh:'Sankey',en:'Sankey'},{zh:'Pie',en:'Pie'}],
   correct:1, exp_zh:'Lex 2014 IEEE TVCG 提出 UpSet plot。', exp_en:'Lex 2014 IEEE TVCG introduced UpSet plot.'},
  {id:'viz-3', topic:'viz', type:'multi',
   q_zh:'color-blind 友善的調色板？（複選）', q_en:'Color-blind-safe palettes? (multi)',
   opts:[{zh:'viridis',en:'viridis'},{zh:'rainbow / jet',en:'rainbow / jet'},
         {zh:'Okabe-Ito',en:'Okabe-Ito'},{zh:'red-green diverging',en:'red-green diverging'}],
   correct:[0,2], exp_zh:'viridis、Okabe-Ito 皆通過色盲驗證。', exp_en:'viridis & Okabe-Ito are color-blind validated.'},

  // ===== Reproducibility =====
  {id:'repro-1', topic:'repro', type:'single',
   q_zh:'動物實驗主要報告規範？', q_en:'Main guideline for animal studies?',
   opts:[{zh:'CONSORT',en:'CONSORT'},{zh:'ARRIVE 2.0',en:'ARRIVE 2.0'},
         {zh:'PRISMA',en:'PRISMA'},{zh:'STROBE',en:'STROBE'}],
   correct:1, exp_zh:'ARRIVE 2.0 (Percie du Sert 2020) 為動物實驗標準。', exp_en:'ARRIVE 2.0 (Percie du Sert 2020) is the animal-study standard.'},
  {id:'repro-2', topic:'repro', type:'single',
   q_zh:'FAIR 的 A 代表？', q_en:'What does "A" stand for in FAIR?',
   opts:[{zh:'Accurate',en:'Accurate'},{zh:'Accessible',en:'Accessible'},
         {zh:'Anonymous',en:'Anonymous'},{zh:'Audited',en:'Audited'}],
   correct:1, exp_zh:'Findable, Accessible, Interoperable, Reusable。', exp_en:'Findable, Accessible, Interoperable, Reusable.'},
  {id:'repro-3', topic:'repro', type:'tf',
   q_zh:'Reproducibility 指的是「給同樣資料同樣程式碼能得到相同結果」。', q_en:'Reproducibility = same data + code → same result.',
   opts:[{zh:'True',en:'True'},{zh:'False',en:'False'}],
   correct:0, exp_zh:'是。replicability 才是「新資料能驗證結論」。', exp_en:'Yes. Replicability = new data confirms conclusion.'},

  // ===== ML =====
  {id:'ml-1', topic:'ml', type:'single',
   q_zh:'盛行率 2% 的二元分類主要指標？', q_en:'Primary metric for 2%-prevalence binary classification?',
   opts:[{zh:'Accuracy',en:'Accuracy'},{zh:'ROC-AUC alone',en:'ROC-AUC alone'},
         {zh:'PR-AUC',en:'PR-AUC'},{zh:'R²',en:'R²'}],
   correct:2, exp_zh:'低盛行率下 PR-AUC 更能反映臨床可用度 (Saito 2015)。', exp_en:'PR-AUC reflects real-world utility at low prevalence (Saito 2015).'},
  {id:'ml-2', topic:'ml', type:'single',
   q_zh:'2024 取代 TRIPOD 2015 的最新規範？', q_en:'2024 successor of TRIPOD 2015?',
   opts:[{zh:'CONSORT-AI',en:'CONSORT-AI'},{zh:'TRIPOD+AI (BMJ 2024)',en:'TRIPOD+AI (BMJ 2024)'},
         {zh:'PRISMA-DTA',en:'PRISMA-DTA'},{zh:'CLAIM',en:'CLAIM'}],
   correct:1, exp_zh:'Collins 2024 BMJ 發表 TRIPOD+AI。', exp_en:'Collins 2024 BMJ published TRIPOD+AI.'},
  {id:'ml-3', topic:'ml', type:'multi',
   q_zh:'下列哪些屬於 data leakage？（複選）', q_en:'Which are data leakage? (multi)',
   opts:[{zh:'在切 train/test 前做 SMOTE',en:'SMOTE before train/test split'},
         {zh:'同一病人切到 train 與 test',en:'Same patient in both train and test'},
         {zh:'同院 CV 充當外部驗證',en:'Same-site CV as external validation'},
         {zh:'記錄學習率',en:'Logging learning rate'}],
   correct:[0,1,2], exp_zh:'前三項都會虛假提高效能。', exp_en:'The first three all artificially inflate performance.'},
  {id:'ml-4', topic:'ml', type:'tf',
   q_zh:'SHAP 值可直接詮釋為因果效應。', q_en:'SHAP values can be read as causal effects.',
   opts:[{zh:'True',en:'True'},{zh:'False',en:'False'}],
   correct:1, exp_zh:'SHAP 反映模型如何使用特徵，不等於因果。', exp_en:'SHAP shows feature use by model, not causal effect.'}
]
};
